project:
  type: book

book:
  title: "Slay Book"
  subtitle: "Resumen Metodol√≥gico de Modelado 4D para Slay"
  author: "Denis Berroeta (<denisberroeta@gmail.cl>)"
  date: "2023-05-28"
  #number-sections: 3
  page-footer: 
    left: "Copyright 2023, [Denis Berroeta](<denis.berroeta@gmail.com>)" 
  chapters:
    - index.qmd
    - slay_project.qmd
    - intro.qmd
    - nerf.qmd
    - instant_ngp.qmd
    - 3d_gaussian_splatting.qmd
    - 4d_gaussian_splatting.qmd
    - references.qmd
    - ref_digital.qmd
        
  appendices:
    - concepts.qmd
    - contacts.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "<denisberroeta@gmail.cl>"
  
execute:
  warning: false
  
editor: source
always_allow_html: true



